# Generated by Django 3.1.1 on 2020-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201012_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='accesspath',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
