# Generated by Django 3.1.1 on 2020-10-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201012_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBKD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('bkd', models.ForeignKey(db_column='bkd_id', on_delete=django.db.models.deletion.CASCADE, to='polls.bkd')),
            ],
        ),
        migrations.RenameField(
            model_name='testpair',
            old_name='pair_id',
            new_name='pair',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='bkd',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='opened',
        ),
        migrations.AlterField(
            model_name='channel',
            name='accesspath',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='testpair',
            unique_together={('tset', 'pair')},
        ),
        migrations.DeleteModel(
            name='BKDToQA',
        ),
        migrations.AddField(
            model_name='unitbkd',
            name='unit',
            field=models.OneToOneField(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='polls.unit'),
        ),
    ]
