# Generated by Django 3.0 on 2020-09-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200907_0243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
