# Generated by Django 3.1.1 on 2020-10-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201016_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
