# Generated by Django 3.1.2 on 2020-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201016_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='answer_set',
            field=models.CharField(max_length=220),
        ),
    ]
