# Generated by Django 3.1.2 on 2020-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20201026_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='answer_set',
            field=models.CharField(max_length=500),
        ),
    ]
